# Generated by Django 5.2.4 on 2026-07-19 13:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "document_uuid",
                    models.UUIDField(
                        blank=True, default=uuid.uuid4, editable=False, null=True
                    ),
                ),
                ("file", models.FileField(upload_to="documents/%Y/%m/%d/")),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("original_name", models.CharField(max_length=255)),
                ("file_type", models.CharField(max_length=20)),
                ("mime_type", models.CharField(blank=True, max_length=100)),
                ("file_size", models.BigIntegerField()),
                ("checksum", models.CharField(max_length=64, unique=True)),
                ("chunk_count", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("processing", "Processing"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                        ],
                        default="uploaded",
                        max_length=20,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(blank=True, max_length=300)),
                ("author", models.CharField(blank=True, max_length=200)),
                ("language", models.CharField(default="unknown", max_length=20)),
                ("page_count", models.PositiveIntegerField(default=0)),
                ("extracted_text", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("processing_time_ms", models.PositiveIntegerField(default=0)),
                ("extraction_version", models.CharField(default="1.0", max_length=20)),
                ("last_accessed_at", models.DateTimeField(blank=True, null=True)),
                ("embedding_model", models.CharField(blank=True, max_length=100)),
                ("indexed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-uploaded_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="documents_d_status_07369e_idx"
                    ),
                    models.Index(
                        fields=["uploaded_at"], name="documents_d_uploade_65506e_idx"
                    ),
                    models.Index(
                        fields=["checksum"], name="documents_d_checksu_fd63d2_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DocumentChunk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "chunk_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("chunk_index", models.PositiveIntegerField()),
                ("page_number", models.PositiveIntegerField(default=1)),
                ("section_title", models.CharField(blank=True, max_length=255)),
                ("text", models.TextField()),
                ("character_count", models.PositiveIntegerField()),
                ("word_count", models.PositiveIntegerField()),
                ("token_count", models.PositiveIntegerField()),
                ("start_char", models.PositiveIntegerField()),
                ("end_char", models.PositiveIntegerField()),
                ("embedding_dimension", models.PositiveIntegerField(default=768)),
                (
                    "embedding_model",
                    models.CharField(default="bge-base-en-v1.5", max_length=100),
                ),
                ("embedding", models.BinaryField(blank=True, null=True)),
                (
                    "faiss_index",
                    models.PositiveIntegerField(blank=True, null=True, unique=True),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("is_indexed", models.BooleanField(default=False)),
                ("indexed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("retrieval_count", models.PositiveIntegerField(default=0)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "ordering": ["document", "chunk_index"],
                "indexes": [
                    models.Index(
                        fields=["document", "page_number"],
                        name="documents_d_documen_1a14ec_idx",
                    ),
                    models.Index(
                        fields=["is_indexed"], name="documents_d_is_inde_43a4e7_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("document", "chunk_index"),
                        name="unique_chunk_per_document",
                    )
                ],
                "unique_together": {("document", "chunk_index")},
            },
        ),
        migrations.CreateModel(
            name="DocumentPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_number", models.PositiveIntegerField()),
                ("text", models.TextField()),
                ("character_count", models.PositiveIntegerField()),
                ("word_count", models.PositiveIntegerField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "ordering": ["document", "page_number"],
                "indexes": [
                    models.Index(
                        fields=["document", "page_number"],
                        name="documents_d_documen_d10ee3_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("document", "page_number"), name="unique_document_page"
                    )
                ],
            },
        ),
    ]
