# Generated by Django 5.2.4 on 2026-07-25 08:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AgentSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "settings_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "name",
                    models.CharField(default="Default Configuration", max_length=100),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("llm_provider", models.CharField(default="ollama", max_length=50)),
                ("llm_model", models.CharField(default="qwen3:8b", max_length=100)),
                ("temperature", models.FloatField(default=0.2)),
                ("top_p", models.FloatField(default=0.95)),
                ("max_output_tokens", models.PositiveIntegerField(default=2048)),
                ("context_window", models.PositiveIntegerField(default=8192)),
                (
                    "embedding_model",
                    models.CharField(default="BAAI/bge-base-en-v1.5", max_length=100),
                ),
                ("embedding_dimension", models.PositiveIntegerField(default=768)),
                ("normalize_embeddings", models.BooleanField(default=True)),
                ("chunk_size", models.PositiveIntegerField(default=400)),
                ("chunk_overlap", models.PositiveIntegerField(default=80)),
                ("preserve_paragraphs", models.BooleanField(default=True)),
                ("preserve_sentences", models.BooleanField(default=True)),
                ("top_k", models.PositiveIntegerField(default=5)),
                ("similarity_threshold", models.FloatField(default=0.65)),
                ("enable_reranker", models.BooleanField(default=False)),
                ("reranker_model", models.CharField(blank=True, max_length=100)),
                ("hybrid_search", models.BooleanField(default=False)),
                ("enable_ocr", models.BooleanField(default=True)),
                ("ocr_language", models.CharField(default="eng", max_length=20)),
                ("stream_response", models.BooleanField(default=True)),
                ("show_sources", models.BooleanField(default=True)),
                ("show_similarity_score", models.BooleanField(default=False)),
                (
                    "system_prompt",
                    models.TextField(
                        default="You are an AI Document Assistant.\n\nAnswer ONLY using the supplied document context.\n\nIf the answer cannot be found in the uploaded documents,\nreply:\n\n'I couldn't find that information in the uploaded documents.'\n\nDo not use your own knowledge."
                    ),
                ),
                ("save_chat_history", models.BooleanField(default=True)),
                ("save_prompts", models.BooleanField(default=True)),
                ("enable_metrics", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Agent Settings",
                "verbose_name_plural": "Agent Settings",
                "ordering": ["-updated_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("is_active",),
                        name="single_active_agent_settings",
                    )
                ],
            },
        ),
    ]
